import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import type { ComponentProps } from 'react';
import { createMemoryRouter, RouterProvider } from 'react-router';
import { beforeEach, describe, expect, test, vi } from 'vitest';
import EditFlashCards, { action, loader } from './edit-flash-cards';
import { getServerClient } from '~/utils/supabase.server';

// This file is generated by an AI so i can have a some sort of an example of writing tests

// Mocking modules
vi.mock('~/utils/supabase.server', () => ({
  getServerClient: vi.fn(),
}));

const mockedgetServerClient = vi.mocked(getServerClient);

function renderEditFlashCards(
  cardsData: { id: string; question: string; answer: string }[] | null,
) {
  const editProps = {
    loaderData: { cardsData, categoryName: 'Science' },
  } as unknown as ComponentProps<typeof EditFlashCards>;
  const router = createMemoryRouter([
    {
      path: '/',
      element: <EditFlashCards {...editProps} />,
    },
  ]);

  return render(<RouterProvider router={router} />);
}

describe('EditFlashCards', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test('renders the category and existing flash cards', () => {
    renderEditFlashCards([
      { id: 'card-1', question: 'What is H2O?', answer: 'Water' },
    ]);

    expect(screen.getByDisplayValue('Science')).toHaveValue('Science');
    expect(screen.getByRole('textbox', { name: 'Question' })).toHaveValue(
      'What is H2O?',
    );
    expect(screen.getByRole('textbox', { name: 'Answer' })).toHaveValue(
      'Water',
    );
    expect(screen.getByText('Flash card number 1')).toBeInTheDocument();
  });

  test('starts with one empty card when the category has no cards', () => {
    renderEditFlashCards(null);

    expect(screen.getByRole('textbox', { name: 'Question' })).toHaveValue('');
    expect(screen.getByRole('textbox', { name: 'Answer' })).toHaveValue('');
  });

  test('updates card fields and adds a new card', async () => {
    const user = userEvent.setup();
    renderEditFlashCards([
      { id: 'card-1', question: 'Old question', answer: 'Old answer' },
    ]);

    await user.clear(screen.getByRole('textbox', { name: 'Question' }));
    await user.type(
      screen.getByRole('textbox', { name: 'Question' }),
      'New question',
    );
    await user.click(screen.getByRole('button', { name: 'Add flash card' }));

    expect(screen.getAllByRole('textbox', { name: 'Question' })).toHaveLength(
      2,
    );
    expect(screen.getByDisplayValue('New question')).toBeInTheDocument();
    expect(screen.getAllByRole('textbox', { name: 'Answer' })).toHaveLength(2);
  });

  test('removes an existing card and includes its id in the form', async () => {
    const user = userEvent.setup();
    renderEditFlashCards([
      { id: 'card-1', question: 'Question', answer: 'Answer' },
      { id: 'card-2', question: 'Keep me', answer: 'Keep answer' },
    ]);

    await user.click(
      screen.getAllByRole('button', { name: 'Remove flash card' })[0],
    );

    expect(screen.queryByDisplayValue('Question')).not.toBeInTheDocument();
    expect(screen.getByDisplayValue('Keep me')).toBeInTheDocument();
    expect(screen.getByDisplayValue('card-1')).toHaveAttribute(
      'name',
      'deletedIds',
    );
  });

  test('does not add a deletion field for a newly added card', async () => {
    const user = userEvent.setup();
    renderEditFlashCards(null);

    await user.click(screen.getByRole('button', { name: 'Remove flash card' }));

    expect(
      screen.queryByRole('textbox', { name: 'Question' }),
    ).not.toBeInTheDocument();
    expect(screen.queryByDisplayValue(/new-/)).not.toBeInTheDocument();
  });
});

// To bardziej zrozumieć
describe('edit flash cards data functions', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  test('loader fetches the category and its cards', async () => {
    const categorySingle = vi.fn().mockResolvedValue({
      data: { name: 'Science' },
    });
    const cardsEq = vi.fn().mockResolvedValue({
      data: [{ id: 'card-1', question: 'Q', answer: 'A' }],
    });
    const categoryBuilder = {
      select: vi.fn(() => ({ eq: vi.fn(() => ({ single: categorySingle })) })),
    };
    const cardsBuilder = {
      select: vi.fn(() => ({ eq: cardsEq })),
    };
    mockedgetServerClient.mockReturnValue({
      supabase: {
        from: vi.fn(table =>
          table === 'categories' ? categoryBuilder : cardsBuilder,
        ),
      },
    } as never);

    await expect(
      loader({
        params: { id: 'category-1' },
        request: new Request('http://test'),
      } as never),
    ).resolves.toEqual({
      cardsData: [{ id: 'card-1', question: 'Q', answer: 'A' }],
      categoryName: 'Science',
    });
  });

  test('action updates, deletes, and inserts cards before redirecting', async () => {
    const categorySingle = vi.fn().mockResolvedValue({
      data: { id: 'category-1', name: 'Science' },
    });
    const categoryUpdate = vi.fn().mockReturnValue({
      eq: vi.fn().mockResolvedValue({ error: null }),
    });
    const cardsDelete = vi.fn().mockReturnValue({
      in: vi.fn().mockResolvedValue({ error: null }),
    });
    const cardsUpdate = vi.fn().mockReturnValue({
      eq: vi.fn().mockResolvedValue({ error: null }),
    });
    const cardsInsert = vi.fn().mockResolvedValue({ error: null });
    const categoryBuilder = {
      select: vi.fn(() => ({
        eq: vi.fn(() => ({ single: categorySingle })),
      })),
      update: categoryUpdate,
    };
    const cardsBuilder = {
      delete: cardsDelete,
      update: cardsUpdate,
      insert: cardsInsert,
    };
    mockedgetServerClient.mockReturnValue({
      supabase: {
        from: vi.fn(table =>
          table === 'categories' ? categoryBuilder : cardsBuilder,
        ),
      },
    } as never);

    const formData = new FormData();
    formData.set('name', 'Biology');
    formData.set('deletedIds', 'card-deleted');
    formData.set('question-card-1', 'Updated question');
    formData.set('answer-card-1', 'Updated answer');
    formData.set('question-new-1', 'New question');
    formData.set('answer-new-1', 'New answer');

    const result = await action({
      params: { id: 'category-1' },
      request: new Request('http://test', { method: 'POST', body: formData }),
    } as never);

    expect(categoryUpdate).toHaveBeenCalledWith({ name: 'Biology' });
    expect(cardsDelete).toHaveBeenCalled();
    expect(cardsUpdate).toHaveBeenCalledWith({
      category_id: 'category-1',
      question: 'Updated question',
      answer: 'Updated answer',
    });
    expect(cardsInsert).toHaveBeenCalledWith([
      {
        category_id: 'category-1',
        question: 'New question',
        answer: 'New answer',
      },
    ]);
    expect(result).toBeInstanceOf(Response);
    expect((result as Response).headers.get('Location')).toBe(
      '/flash-cards/Biology',
    );
  });
});
